"use client";
import Link from "next/link";
import { startTransition, useActionState, useEffect, useRef, useState } from "react";
import { FileUp, Users, WalletCards, CalendarDays } from "lucide-react";
import { statementAction } from "@/app/spending/statements/actions";
import { formats,type Draft,type Account,type Entry,type UploadState,type StatementRow } from "@/lib/statements/model";
import { classifications, classificationFor, categoryLabel, summarizeSpending } from "@/lib/statements/review";
import type { loadStatements } from "@/lib/statements/repository";
type Data=Awaited<ReturnType<typeof loadStatements>>;
const input="mt-1 block w-full rounded-xl border bg-background px-3 py-2 text-sm";
const button="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50";
const panel="rounded-2xl border bg-card p-5 shadow-sm sm:p-6";
const currency=(minor:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(minor/100);
const initial:UploadState={status:"idle",message:""};
export function StatementDashboard({data,defaultMonth}:{data:Data;defaultMonth:string}) {
  const [state,action,pending]=useActionState(statementAction,initial);
  const [month,setMonth]=useState(defaultMonth),[owner,setOwner]=useState("all");
  const me=data.members.find(member=>member.user_id===data.userId);
  const filtered=data.entries.filter(row=>row.direction==="debit"&&row.date.startsWith(month)&&(owner==="all"||data.accounts.find(account=>account.id===row.account_id)?.owner_id===owner));
  const {total,emi,investments,categories:categoryTotals}=summarizeSpending(filtered);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Shared household · statement-based</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Spending, together</h1><p className="mt-3 max-w-2xl text-muted-foreground">Upload statements once. Review what matters. See one household picture.</p></div><Link href="/spending/review" className="text-sm underline">Synthetic test sandbox</Link></div>
    {state.message&&<div role={state.status==="error"?"alert":"status"} className="rounded-xl border bg-muted/40 p-4">{state.message}{state.errors?.map(error=><p key={error} className="mt-2 text-sm">{error}</p>)}</div>}
    {!me ? <section className={panel}><h2 className="text-xl font-bold">Create or join your household</h2><p className="my-3 text-muted-foreground">Two separate sign-ins, one shared spending space. Nutrition and existing personal data remain private.</p>
      {data.invites.map(invite=><form action={action} key={invite.household_id} className="my-4 space-y-3 rounded-xl border p-4"><input type="hidden" name="operation" value="accept"/><input type="hidden" name="value" value={invite.household_id}/><p>Invitation for your verified sign-in email. Joining shares all statement imports in this household.</p><Consent>Join and share household spending</Consent><button className={button} disabled={pending}>Accept household invitation</button></form>)}
      <form action={action} className="space-y-3"><input type="hidden" name="operation" value="create"/><Consent>Create a household and share future confirmed imports with my invited partner</Consent><button className={button} disabled={pending}>Create household</button></form>
    </section> : <>
      <div className="flex flex-wrap items-end gap-4"><label className="text-sm">Calendar month<input type="month" className={input} value={month} onChange={event=>setMonth(event.target.value)}/></label><label className="text-sm">Account owner<select className={input} value={owner} onChange={event=>setOwner(event.target.value)}><option value="all">Everyone in household</option>{data.members.map(member=><option key={member.user_id} value={member.user_id}>{member.user_id===data.userId?"Me":member.display_name}</option>)}</select></label><span className="pb-2 text-sm text-muted-foreground">INR · dates shown on statements</span></div>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Monthly spending summary"><Metric icon={<WalletCards className="size-5"/>} label="Outgoing expenses" value={currency(total)}/><Metric icon={<CalendarDays className="size-5"/>} label="Monthly EMI expenses included" value={currency(emi)}/><Metric icon={<WalletCards className="size-5"/>} label="Investments · separate from spending" value={currency(investments)}/><Metric icon={<Users className="size-5"/>} label="Shared accounts" value={String(data.accounts.length)}/></section>
      <p className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">Outgoing expenses from confirmed debits only—not a bank balance or a complete-month guarantee. Credits and refunds are hidden and do not reduce this total. Investments are separate; card repayments, transfers and original financed purchases are excluded. Monthly EMI amounts count once.</p>
      <section className={panel}><div className="flex items-center gap-3"><FileUp className="size-6 text-primary"/><h2 className="text-xl font-bold">Upload statements</h2></div><p className="mt-2 text-sm text-muted-foreground">One batch for SBI bank, SBI Card and Axis Card. Other formats are reported as unsupported. Up to five unlocked, text-based PDFs; 3 MB combined.</p>
        <form action={action} className="mt-5 space-y-4"><input type="hidden" name="operation" value="upload"/><label className="block rounded-xl border-2 border-dashed p-5 text-sm font-medium">Choose your PDF statements<input type="file" name="files" accept="application/pdf,.pdf" multiple required className="mt-3 block w-full text-sm" disabled={pending} onChange={event=>{const files=Array.from(event.currentTarget.files??[]);event.currentTarget.setCustomValidity(files.length>5||files.reduce((sum,file)=>sum+file.size,0)>3*1024*1024?"Choose at most five PDFs, 3 MB combined.":"");event.currentTarget.reportValidity();}}/></label><Consent>I agree to temporary PDF processing and sharing confirmed transactions with my household. PDFs are not stored; extracted review data expires after 24 hours.</Consent><button className={button} disabled={pending}><FileUp className="size-4"/>{pending?"Working…":"Extract and preview"}</button></form>
      </section>
      {data.drafts.map(draft=><Review key={draft.id} draft={draft} accounts={data.accounts} entries={data.entries} imports={data.imports} action={action} pending={pending} state={state}/>)}
      <details className={panel} open={!data.accounts.length}><summary className="cursor-pointer text-lg font-bold">Household & accounts</summary><div className="mt-4 grid gap-6 lg:grid-cols-2"><section className="space-y-3"><h3 className="font-semibold">Shared accounts</h3><p className="text-sm text-muted-foreground">Use nicknames and optional last four digits only. All confirmed imports are visible to both household members.</p>{data.accounts.map(account=><p key={account.id} className="rounded-xl bg-muted/50 p-3 text-sm">{account.label} · {account.format} {account.last_four&&`· ending ${account.last_four}`} · {data.members.find(member=>member.user_id===account.owner_id)?.display_name??"Former household member"}</p>)}
        <form action={action} className="space-y-3"><input type="hidden" name="operation" value="account"/><label className="block text-sm">Account nickname<input name="label" maxLength={60} required placeholder="My SBI savings" className={input}/></label><label className="block text-sm">Statement format<select name="format" className={input}>{formats.map(format=><option key={format}>{format}</option>)}</select></label><label className="block text-sm">Account owner<select name="owner" className={input} defaultValue={data.userId}>{data.members.map(member=><option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select></label><label className="block text-sm">Last four digits (optional)<input name="last_four" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} className={input}/></label><button className={button} disabled={pending}>Add shared account</button></form></section>
        <section className="space-y-4"><h3 className="font-semibold">Household members</h3>{data.members.map(member=><div key={member.user_id} className="rounded-xl bg-muted/50 p-3 text-sm"><p>{member.display_name} · {member.role}</p>{me.role==="owner"&&member.role!=="owner"&&<form action={action} className="mt-3 space-y-2"><input type="hidden" name="operation" value="remove"/><input type="hidden" name="value" value={member.user_id}/><Consent>Revoke this member’s access; existing shared records remain</Consent><button disabled={pending} className={button}>Remove member</button></form>}</div>)}
          {me.role==="owner"&&data.members.length<2&&<form action={action} className="space-y-3"><input type="hidden" name="operation" value="invite"/><label className="block text-sm">Partner’s Google sign-in email<input type="email" name="value" required maxLength={254} className={input}/></label><Consent>Invite this person to view all household spending</Consent><button className={button} disabled={pending}>Save invitation</button><p className="text-xs text-muted-foreground">No email is sent. Ask your partner to sign in and open Spending within seven days.</p></form>}
          {data.invites.map(invite=><form key={invite.household_id} action={action} className="space-y-2"><p className="text-sm">Pending: {invite.email}</p><input type="hidden" name="operation" value="revoke"/><Consent>Cancel this pending invitation</Consent><button className={button} disabled={pending}>Revoke invitation</button></form>)}
          {me.role==="member"&&<form action={action} className="space-y-2"><input type="hidden" name="operation" value="leave"/><Consent>Leave this household. Existing shared records remain there; I lose access.</Consent><button className={button} disabled={pending}>Leave household</button></form>}
        </section></div></details>
      <div className="grid gap-6 lg:grid-cols-2"><section className={panel}><h2 className="text-xl font-bold">Where your money went</h2><p className="mt-2 text-sm text-muted-foreground">Share of outgoing expenses for the selected month and owner. Investments are not included.</p>{!categoryTotals.length?<p className="mt-4 text-muted-foreground">No confirmed expenses for this selection.</p>:<ul className="mt-4 space-y-3">{categoryTotals.map(row=><li key={row.category} className="space-y-2"><div className="flex flex-wrap justify-between gap-2"><span>{row.category}</span><span><strong>{currency(row.amount)}</strong><span className="ml-2 text-muted-foreground">{row.percentage.toFixed(1)}%</span></span></div><div aria-hidden="true" className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${row.percentage}%`}}/></div></li>)}</ul>}</section><section className={panel}><h2 className="text-xl font-bold">Statement coverage</h2><p className="mt-2 text-sm text-muted-foreground">Imported periods are not proof of completeness if rows were excluded. Check every account for missing dates.</p>{data.accounts.map(account=>{const imports=data.imports.filter(item=>item.account_id===account.id);return <div key={account.id} className="mt-4 border-t pt-3 text-sm"><strong>{account.label}</strong>{!imports.length?<p>No statement imported.</p>:imports.slice(0,4).map(item=><p key={item.id}>{item.period_start??"Unknown start"} → {item.period_end??"Unknown end"} · uploaded {item.created_at.slice(0,10)}</p>)}</div>;})}</section></div>
      <section className={panel}><h2 className="text-xl font-bold">Confirmed debits · {filtered.length}</h2><p className="mt-2 text-sm text-muted-foreground">Only debits are shown. Your category determines whether a debit counts as an expense, an investment or an excluded movement. Corrections are shared and audited.</p><div className="mt-4 space-y-3">{filtered.map(row=><details key={`${row.id}-${row.revision}`} className="rounded-xl border p-3"><summary className="cursor-pointer text-sm"><strong>{row.merchant}</strong> · {row.date} · {currency(row.amount)} {row.direction==="credit"?"Cr":"Dr"}<span className="mt-1 block text-muted-foreground">{data.accounts.find(account=>account.id===row.account_id)?.label} · {categoryLabel(row)}</span></summary><form action={action} className="mt-4 space-y-3"><input type="hidden" name="operation" value="correct"/><input type="hidden" name="entry" value={row.id}/><input type="hidden" name="revision" value={row.revision}/><label className="block text-sm">Merchant<input name="merchant" defaultValue={row.merchant} required maxLength={160} className={input}/></label><label className="block text-sm">Category<select name="classification" defaultValue={classificationFor(row)} className={input} required><CategoryOptions/></select></label><Consent>Apply this correction to our shared spending</Consent><button className={button} disabled={pending}>Save correction</button></form></details>)}</div></section>
    </>}
  </div>;
}
function Consent({children}:{children:React.ReactNode}) {return <label className="flex items-start gap-2 text-sm"><input type="checkbox" name="consent" value="yes" required className="mt-1"/>{children}</label>;}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}) {return <div className={panel}><div className="text-primary">{icon}</div><p className="mt-4 text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p></div>;}
function Review({draft,accounts,entries,imports,action,pending,state}:{draft:Draft;accounts:Account[];entries:Entry[];imports:Data["imports"];action:(form:FormData)=>void;pending:boolean;state:UploadState}) {
  const [selected,setSelected]=useState<Record<number,string>>({}); const [bulk,setBulk]=useState(false);
  const feedback=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(state.status==="error"&&state.reviewId===draft.id) feedback.current?.focus();},[state,draft.id]);
  return <section className={panel}><h2 className="text-xl font-bold">Combined preview · {draft.files.length} files</h2><p className="mt-2 text-sm text-muted-foreground">Private draft until confirmation. Expires {draft.expires_at.replace("T"," ").slice(0,16)} UTC. Uncheck rows you do not want to import. Credit rows are hidden and excluded from this import. Choose a category for unclear debits. Source row numbers match the extracted statement.</p>
    {/* Dispatch explicitly so a returned validation error does not reset the reviewed form. */}
    <form onSubmit={event=>{event.preventDefault();if(pending)return;const form=new FormData(event.currentTarget);startTransition(()=>action(form));}} className="mt-5 space-y-5"><input type="hidden" name="operation" value="confirm"/><input type="hidden" name="draft" value={draft.id}/>
      {draft.files.map((file,fi)=>{const matching=accounts.filter(account=>account.format===file.format);const account=selected[fi]??(matching.length===1?matching[0].id:"");const already=imports.some(item=>item.account_id===account&&item.file_hash===file.hash);return <fieldset key={fi} className="min-w-0 space-y-3 rounded-xl border p-4"><legend className="px-2 font-semibold">{file.label} · {file.rows.filter(row=>row.direction==="debit").length} debit rows</legend><p className="text-sm">Statement period: {file.start??"Unknown"} → {file.end??"Unknown"}</p><label className="block text-sm">Assign to shared account<select name={`account-${fi}`} required className={input} value={account} onChange={event=>setSelected({...selected,[fi]:event.target.value})}><option value="">Choose account (add one below if needed)</option>{matching.map(item=><option key={item.id} value={item.id}>{item.label}{item.last_four?` · ${item.last_four}`:""}</option>)}</select></label>
        {file.warnings.map(warning=><p key={warning} className="text-sm text-amber-800">{warning}</p>)}{already&&<p className="font-semibold">This exact PDF was already confirmed for this account. It will be skipped.</p>}
        {!file.rows.some(row=>row.direction==="debit")&&<p className="text-sm text-muted-foreground">No debit rows in this file. Nothing from this file will be added to expenses.</p>}
        <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr><th className="p-2">Include</th><th className="p-2">Date / amount</th><th className="p-2">Merchant</th><th className="p-2">Category</th></tr></thead><tbody>{file.rows.map((row,ri)=>{
          if(row.direction==="credit") return null;
          const duplicate=entries.some(entry=>entry.account_id===account&&entry.fingerprint===row.fingerprint)||file.rows.slice(0,ri).some(item=>item.fingerprint===row.fingerprint)||draft.files.slice(0,fi).some((previous,pfi)=>{const opts=accounts.filter(a=>a.format===previous.format);const previousAccount=selected[pfi]??(opts.length===1?opts[0].id:"");return previousAccount===account&&previous.rows.some(item=>item.fingerprint===row.fingerprint);});
          return <ReviewRow key={`${account}-${ri}`} row={row} fi={fi} ri={ri} duplicate={duplicate} already={already} bulk={bulk}/>;
        })}</tbody></table></div>
      </fieldset>;})}
      <button type="button" className="rounded-xl border px-4 py-2 text-sm" disabled={pending||bulk} onClick={()=>{if(window.confirm("Mark untouched unresolved debit rows as purchase expenses? Check transfers and card repayments first."))setBulk(true);}}>Mark untouched unresolved debits as purchases</button>
      <p className="text-sm text-muted-foreground">The bulk button assigns the suggested purchase category only to untouched, unresolved debits. Check investments, transfers and card repayments before confirming.</p>
      {state.status==="error"&&state.reviewId===draft.id&&<div ref={feedback} tabIndex={-1} role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">{state.message}</div>}
      <label className="flex items-start gap-2 text-sm"><input type="checkbox" name="confirm" value="yes" required className="mt-1"/>I checked included rows, accounts, duplicates and EMI treatment. Save to our shared household.</label><button className={button} disabled={pending}>{pending?"Saving…":"Confirm combined import"}</button>
    </form>
    <form action={action} className="mt-4"><input type="hidden" name="operation" value="discard"/><input type="hidden" name="draft" value={draft.id}/><button className="text-sm underline" disabled={pending}>Discard this review</button></form>
  </section>;
}
function ReviewRow({row,fi,ri,duplicate,already,bulk}:{row:StatementRow;fi:number;ri:number;duplicate:boolean;already:boolean;bulk:boolean}) {
  const prefix=`${fi}-${ri}`;
  const [include,setInclude]=useState(!duplicate&&!already),[merchant,setMerchant]=useState(row.merchant),[manualCategory,setCategory]=useState<string|null>(null),[keep,setKeep]=useState(false);
  const classification=manualCategory??classificationFor(bulk&&row.kind==="review"?{...row,kind:"expense"}:row);
  return <tr className="border-t align-top"><td className="p-2"><input aria-label={`Include row ${ri+1} in file ${fi+1}`} type="checkbox" name={`include-${prefix}`} value="yes" checked={include} onChange={event=>setInclude(event.target.checked)}/></td><td className="whitespace-nowrap p-2"><p>Source row {ri+1} · {row.date}</p><strong>{currency(row.amount)} {row.direction==="credit"?"Cr":"Dr"}</strong></td><td className="p-2"><input aria-label={`Merchant row ${ri+1} file ${fi+1}`} name={`merchant-${prefix}`} value={merchant} onChange={event=>setMerchant(event.target.value)} maxLength={160} className={input}/>{row.warning&&<p className="mt-2 max-w-sm text-xs text-amber-800">{row.warning}</p>}{duplicate&&<label className="mt-2 flex max-w-sm items-start gap-2 text-xs text-amber-900"><input type="checkbox" name={`duplicate-${prefix}`} value="yes" checked={keep} onChange={event=>setKeep(event.target.checked)}/>Possible duplicate. Check only if this is a distinct transaction, then include the row.</label>}</td><td className="p-2"><select aria-label={`Category row ${ri+1} file ${fi+1}`} name={`classification-${prefix}`} value={classification} onChange={event=>setCategory(event.target.value)} className={input}><CategoryOptions/></select></td></tr>;
}

function CategoryOptions() {
  return <><option value="review">Needs review — choose category</option>{(["Expense","Excluded from expenses"] as const).map(group=><optgroup key={group} label={group}>{classifications.filter(option=>option.group===group).map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</optgroup>)}</>;
}
