import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
test("Gmail migration enforces ownership, encrypted-token boundaries, limits and disconnect", async () => {
  const db=new PGlite();
  const owner="11111111-1111-4111-8111-111111111111", other="22222222-2222-4222-8222-222222222222";
  const ciphertext="v1."+"synthetic-encrypted-placeholder".repeat(3);
  try {
    await db.exec(`create role anon; create role authenticated; create schema auth;
      create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'', true), '''')::uuid';
      grant usage on schema auth to authenticated,anon;
      create table public.users(id uuid primary key);`);
    await db.exec(await readFile(new URL("../../../supabase/migrations/202609170001_gmail_foundation.sql",import.meta.url),"utf8"));
    await db.query("insert into public.users values($1),($2)",[owner,other]);
    await db.exec("set role authenticated");
    const asUser=id=>db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
    await asUser(owner);
    const save=(id,email,enabled=true)=>db.query("select public.save_financial_sender($1,$2,'Synthetic sender','Synthetic institution',$3)",[id,email,enabled]);
    await save(null,"alerts@example.com");
    await assert.rejects(save(null,"alerts@example.com"));
    await assert.rejects(save(null,"*@example.com"));
    const sender=(await db.query("select * from public.financial_senders")).rows[0];
    await save(sender.id,"alerts@example.com",false);
    assert.equal((await db.query("select enabled from public.financial_senders")).rows[0].enabled,false);
    for(let i=1;i<20;i++) await save(null,`alerts${i}@example.com`);
    await assert.rejects(save(null,"extra@example.com"),/Sender limit/);
    await assert.rejects(db.query("insert into public.financial_senders(user_id,sender_email,sender_name,institution) values($1,'b@example.com','a','b')",[owner]),/permission denied/);
    await db.query("select public.connect_gmail('mailbox@example.com',$1)",[ciphertext]);
    await assert.rejects(db.query("select public.connect_gmail('otherbox@example.com',$1)",[ciphertext]));
    const connection=(await db.query("select id,email from public.gmail_connections")).rows[0];
    await assert.rejects(db.query("select encrypted_refresh_token from public.gmail_connections"),/permission denied/);
    await assert.rejects(db.query("update public.gmail_connections set email='x@example.com'"),/permission denied/);
    assert.equal((await db.query("select public.claim_gmail_check() as token")).rows[0].token,ciphertext);
    await assert.rejects(db.query("select public.claim_gmail_check()"),/wait one minute/);
    await asUser(other);
    assert.equal((await db.query("select id from public.gmail_connections")).rows.length,0);
    assert.equal((await db.query("select * from public.financial_senders")).rows.length,0);
    await assert.rejects(save(sender.id,"evil@example.com"),/unavailable/);
    await assert.rejects(db.query("select public.remove_financial_sender($1)",[sender.id]),/unavailable/);
    assert.equal((await db.query("select public.disconnect_gmail($1) as token",[connection.id])).rows[0].token,null);
    await assert.rejects(db.query("select public.claim_gmail_check()"));
    await asUser(owner);
    assert.equal((await db.query("select public.disconnect_gmail($1) as token",[connection.id])).rows[0].token,ciphertext);
    assert.equal((await db.query("select id from public.gmail_connections")).rows.length,0);
    assert.equal((await db.query("select count(*) as n from public.financial_senders")).rows[0].n,20);
    await db.query("select public.remove_financial_sender($1)",[sender.id]);
    await db.exec("reset role; set role anon");
    await assert.rejects(db.query("select public.claim_gmail_check()"),/permission denied/);
    await assert.rejects(db.query("select id from public.gmail_connections"),/permission denied/);
    await assert.rejects(db.query("select * from public.financial_senders"),/permission denied/);
  } finally {await db.close();}
});
